### ISSUE TITLE
Unable to compile on Mac

### ISSUE THREAD

**Issue by robert-blankenship** [KualiCo/nats-streaming-console#18]
<img width="884" alt="Screen Shot 2020-07-22 at 6 26 12 PM" src="https://user-images.githubusercontent.com/7118222/88244505-e6cb0d80-cc48-11ea-9d3d-c0d8e15d0337.png">

**Comment by artemseleznev** [comment]
@robert-blankenship at first you should run build-css as it was showed in readme https://github.com/KualiCo/nats-streaming-console/blob/master/README.md
